	<DIV id="footer" class="clear">
		<div class="footmenu">
		<ul>
			<li><a href="index.php" class="mm mm01" id="mm_01">HOME</a></li>
			<li><a href="p_joblist.php" class="mm mm02" id="mm_02">求人情報</a></li>
			<li><a href="p_candidates_strength.php">紹介得意分野</a></li>
			<li><a href="p_corporation.php">会社概要</a></li>
			<li><a href="http://yahoo.jp/VPGrHA" target="_blank">アクセス</a></li>
			<li><a href="p_corporation_recruit.php">当社採用情報</a></li>
			<li><a href="mailto:<?php echo($mailto); ?>" class="mm mm06" id="mm_06">お問い合せ</a></li>
			<li><a href="p_corporation_policy.php" class="mm mm07" id="mm_07" style="border-right:0px none;">個人情報保護方針</a></li>
		</ul>
		<p class="copy">&copy; 2014 Oaks International Co., Ltd. All Rights Reserved.</p>
	</DIV>

	</DIV>
	</DIV>
</BODY>
</HTML>